namespace: "morpheusdata"
name: "morpheus"
version: "0.1.2"
readme: "README.md"
authors:
    - "Nick Celebic (https://www.github.com/tryfan)"
license:
    - "Apache-2.0"
tags:
    - morpheus
    - cloud
    - collection
repository: "https://www.github.com/tryfan/ansible-morpheus-collection"
build_ignore:
    - "Dockerfile"
    - "*.code-workspace"
    - "azure-pipelines.yml"
    - "testruns"
    - ".idea"